
name: fake_call_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.0
  flutter_local_notifications: ^17.0.0
  audioplayers: ^5.2.1
  wakelock_plus: ^1.1.4
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  timezone: ^0.9.4
  equatable: ^2.0.8
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
